# -*- coding: utf-8 -*-
"""grade_calculator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RpPBq2nZn-yGe9B2db7C7fE3S9Pjlb1O
"""

def calculate_gpa(scores):
  if not scores:
    return 0.0
  try:
    gpa=sum(scores)/len(scores)
    return round(gpa,2)
  except (TypeError, ValueError):
    return 0.0
def classify_student(gpa):
  if gpa>=9:
    return "Excellent"
  elif gpa >=8:
    return "Good"
  elif gpa>=6.5:
    return "Fair"
def get_top_student(students_list):
  if not students_list:
    return None
  top_student=max(students_list, key=lambda student: calculate_gpa(student['scores']))
  return top_student